{% set version = "1.26.1" %}

package:
  name: tabulator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tabulator/tabulator-{{ version }}.tar.gz
  sha256: 30d5445b13b71d98b5d35f488f633ba2960eb4ad9955510286e4da8f8fa3a96c

build:
  number: 0
  noarch: python
  entry_points:
    - tabulator = tabulator.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cchardet >=1.0
    - click >=6.0
    - ijson >=2.0
    - jsonlines >=1.1
    - linear-tsv >=1.0
    - openpyxl >=2.4,<2.5
    - requests >=2.8
    - six >=1.9
    - sqlalchemy >=0.9.6
    - unicodecsv >=0.14
    - xlrd >=1.0

test:
  imports:
    - tabulator
    - tabulator.loaders
    - tabulator.parsers
    - tabulator.writers
  commands:
    - tabulator --help

about:
  home: https://github.com/frictionlessdata/tabulator-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Consistent interface for stream reading and writing tabular data (csv/xls/json/etc)

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
