{% set version = "1.33.0" %}

package:
  name: tabulator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tabulator/tabulator-{{ version }}.tar.gz
  sha256: 1c30f0c1e9505ee3a20432a84f8c46954c50f45825fed471ba27a25a311b24a2

build:
  number: 0
  noarch: python
  entry_points:
    - tabulator = tabulator.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    # General
    - six >=1.9
    - click >=6.0
    - requests >=2.8
    - cchardet >=1.0
    - boto3 >=1.9
    # Format: csv
    - unicodecsv >=0.14
    # Format: json
    - ijson >=2.5
    # Format: ndjson
    - jsonlines >=1.1
    # Format: sql
    - sqlalchemy >=0.9.6
    # Format: tsv
    - linear-tsv >=1.0
    # Format: xls
    - xlrd >=1.0
    # Format: xlsx
    - openpyxl >=2.6

test:
  imports:
    - tabulator
    - tabulator.loaders
    - tabulator.parsers
    - tabulator.writers
  commands:
    - tabulator --help

about:
  home: https://github.com/frictionlessdata/tabulator-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Consistent interface for stream reading and writing tabular data (csv/xls/json/etc)

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
